[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/index.html"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/admin.html"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"
