[[headers]]
  for = "/*"
  [headers.values]
    # Substitua abaixo pela sua política desejada,
    # ou use 'default-src * 'unsafe-inline' 'unsafe-eval';' para desativar as restrições
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline';"
